#immagine di base
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.12.0-cpu-py310 

#file {py locale} {py nel container}
RUN pip install matplotlib numpy pandas scikit-learn matplotlib tensorflow keras pillow

ADD ./train.py /opt/ml/code/train.py

#cambio valore di una variabile globale
ENV SAGEMAKER_PROGRAM train.py