FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.12.1-cpu

# Aggiungi i requisiti
ADD ./requirements.inference.txt /opt/requirements.txt
RUN pip3 install -r /opt/requirements.txt

# Copia lo script di inferenza
ADD ./inference.py /opt/program/inference.py
ADD ./pippo.sh /opt/pippo.sh

# Imposta le variabili d'ambiente
ENV FLASK_APP=/opt/program/inference.py

# Imposta il comando di avvio corretto
ENTRYPOINT ["/opt/pippo.sh"]