FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.12.1-cpu

ADD ./requirements.inference.txt /opt/requirements.txt
RUN pip3 install -r/opt/requirements.txt

ADD ./inference.py /opt/inference.py

ENV FLASK_APP=/opt/inference.py
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]